version: '3'

volumes: 
    nwvol:

networks: 
    nwnet:

services: 
    nwdb:
        image: tp/nwdb:v1
        build:
            context: ./database
        environment: 
        - MYSQL_ROOT_PASSWORD=changeit
        networks: 
        - nwnet
        volumes: 
        - nwvol:/var/lib/mysql

    nwapp:
        image: tp/nwapp:v1
        build:
            context: ./server
        environment: 
            - DB_HOST=nwdb
            - DB_PORT=3306
            - DB_USER=root
            - DB_PASSWORD=changeit
        networks: 
            - nwnet
