--- 
    apiVersion: v1
    kind: ConfigMap
    metadata:
       namespace: myns
       name: northwind-app-configmap
    
    data:
       DB_USER: root
       DB_HOST: northwind-db-service.myns.svc.cluster.local
       
---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
       name: northwind-app-deploy
       namespace: myns
       labels:
          name: northwind-app
          tier: app
    
    spec:
       replicas: 2
       selector:
          matchLabels:
             name: northwind-app-pod
    
       strategy:
          type: RollingUpdate
          rollingUpdate:
             maxSurge: 1
             maxUnavailable: 1
       template:
          metadata:
             name: northwind-app-pod
             labels:
                name: northwind-app-pod
          spec:
             containers:
             - name: northwind-app-container
               image: stackupiss/northwind-app:v1
               imagePullPolicy: Always
               ports:
               - name: app-port
                 containerPort: 3000
               env:
               - name: DB_PASSWORD
                 valueFrom:
                    secretKeyRef:
                      name: northwind-db-secret
                      key: MYSQL_ROOT_PASSWORD
               - name: INSTANCE_IP_ADDRESS
                 valueFrom:
                    fieldRef:
                       fieldPath: status.podIP
               envFrom:
                  - configMapRef:
                     name: northwind-app-configmap
    
--- 
    apiVersion: v1
    kind: Service
    metadata:
       name: northwind-app-service
       namespace: myns
       labels:
          name: northwind-app-service
    spec:
       type: LoadBalancer
       selector:
          name: northwind-app-pod
       ports:
       - name: http
         port: 80
         targetPort: app-port