---
    apiVersion: v1
    kind: Service
    metadata:
        name: app2-svc
    spec:
        selector:
            app: app
            version: v2
        type: ClusterIP
        ports:
            - port: 80
              targetPort: 3000
        
---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
        name: app2-deployment
        labels:
            app: app
            version: v2
    spec:
        replicas: 1
        selector:
            matchLabels:
                app: app
                version: v2
        template:
            metadata:
                labels:
                    app: app
                    version: v2
            spec:
                containers:
                - image: stackupiss/northwind-app:v2
                  name: app2
                  env:
                    - name: DB_PASSWORD
                      value: "changeit"
                    - name: DB_USER
                      value: "root"
                    - name: DB_HOST
                      value: "mydb-svc"
                  imagePullPolicy: Always
                  ports:
                  - containerPort: 3000
    